version: 2
updates:
  - package-ecosystem: "docker"
    directories:
      - "/dockerfile/flex"
      - "/dockerfile/flex-ce"
    ignore:
      - dependency-name: "amazoncorretto"
        update-types: ["version-update:semver-major"]
      - dependency-name: "eclipse-temurin"
        update-types: ["version-update:semver-major"]
    schedule:
      interval: "daily"
    reviewers:
      - "ceels"
      - "nvenegas"
      - "ShanelleFactorHouse"
